"""DispatchDesk visual theme."""

import gradio as gr

THEME = gr.themes.Base(
    primary_hue="rose",
    secondary_hue="rose",
    neutral_hue="gray",
    # Gradio 6.29 compares the first font with built-in Font objects at launch.
    font=[gr.themes.GoogleFont("DM Sans", weights=[400, 500, 600, 700]), "sans-serif"],
).set(
    color_accent="#87364b",
    color_accent_soft="#34272c",
    color_accent_soft_dark="#34272c",
    body_background_fill="#191919",
    body_background_fill_dark="#191919",
    body_text_color="#f2eee9",
    body_text_color_dark="#f2eee9",
    body_text_color_subdued="#bcb7b1",
    body_text_color_subdued_dark="#bcb7b1",
    block_background_fill="#222222",
    block_background_fill_dark="#222222",
    code_background_fill="#2e2e2e",
    code_background_fill_dark="#2e2e2e",
    block_border_color="#3d3a38",
    block_border_color_dark="#3d3a38",
    block_radius="12px",
    block_label_background_fill="transparent",
    block_label_background_fill_dark="transparent",
    block_label_text_color="#bcb7b1",
    block_label_text_color_dark="#bcb7b1",
    input_background_fill="#222222",
    input_background_fill_dark="#222222",
    input_border_color="#3d3a38",
    input_border_color_dark="#3d3a38",
    input_border_color_focus="#79505c",
    input_border_color_focus_dark="#79505c",
    link_text_color="#d3a3af",
    link_text_color_dark="#d3a3af",
    link_text_color_hover="#e7bcc7",
    link_text_color_hover_dark="#e7bcc7",
    button_primary_background_fill="#87364b",
    button_primary_background_fill_dark="#87364b",
    button_primary_background_fill_hover="#9b4058",
    button_primary_background_fill_hover_dark="#9b4058",
    button_primary_text_color="#fbf7f3",
    button_primary_text_color_dark="#fbf7f3",
    button_primary_border_color="#87364b",
    button_primary_border_color_dark="#87364b",
    button_primary_border_color_hover="#9b4058",
    button_primary_border_color_hover_dark="#9b4058",
    button_secondary_background_fill="#282828",
    button_secondary_background_fill_dark="#282828",
    button_secondary_background_fill_hover="#2e2e2e",
    button_secondary_background_fill_hover_dark="#2e2e2e",
    button_secondary_text_color="#f2eee9",
    button_secondary_text_color_dark="#f2eee9",
    button_secondary_border_color="#3d3a38",
    button_secondary_border_color_dark="#3d3a38",
    button_secondary_border_color_hover="#79505c",
    button_secondary_border_color_hover_dark="#79505c",
    button_border_width="1px",
    button_large_radius="10px",
)
